databridge/__init__.py,sha256=eto6CoKa63KGGEqT28JvpZJy6_ldYespuXrjcBhoedc,198
databridge/client.py,sha256=etx6lB0sjCmmbezc_hUECUOgPShw545TJ9wVEUNTrGM,7066
databridge/exceptions.py,sha256=3jqkdWNxOmPudpBR2Fjze6xcfk4235RXvbLMY0dpA3M,268
databridge_client-0.1.1.dist-info/METADATA,sha256=3KkrbbTt9FgNXcT4Tl9sFKICYDfausMGiXpw2D91rAM,959
databridge_client-0.1.1.dist-info/WHEEL,sha256=C2FUgwZgiLbznR-k0b_5k3Ai_1aASOXDss3lzCUsUug,87
databridge_client-0.1.1.dist-info/RECORD,,
