databridge/__init__.py,sha256=eto6CoKa63KGGEqT28JvpZJy6_ldYespuXrjcBhoedc,198
databridge/client.py,sha256=F3nsI-Ip4Dy69qqXvVwKFrPXC5Njjs8cpN6eaninnlQ,6101
databridge/exceptions.py,sha256=3jqkdWNxOmPudpBR2Fjze6xcfk4235RXvbLMY0dpA3M,268
databridge_test-0.1.1.dist-info/METADATA,sha256=_eerelgTvainr6aVC_hc3eQFffu3Ka9X_gFYhlJRm1Q,944
databridge_test-0.1.1.dist-info/WHEEL,sha256=C2FUgwZgiLbznR-k0b_5k3Ai_1aASOXDss3lzCUsUug,87
databridge_test-0.1.1.dist-info/RECORD,,
