databridge/__init__.py,sha256=9HzZYzjPYvoLiVyiUEr7rVGLVMEhJ-TFvdtQwz1IV-E,198
databridge/client.py,sha256=1-eIRxcvLfwsbbbOIaNfiR8oI5PZCElUT-byaCIQZdA,7106
databridge/exceptions.py,sha256=3jqkdWNxOmPudpBR2Fjze6xcfk4235RXvbLMY0dpA3M,268
databridge_client-0.1.2.dist-info/METADATA,sha256=zQG2lPr9xXaciKji4bigFdNOIlJeZs10h3yl2gdHwpA,967
databridge_client-0.1.2.dist-info/WHEEL,sha256=C2FUgwZgiLbznR-k0b_5k3Ai_1aASOXDss3lzCUsUug,87
databridge_client-0.1.2.dist-info/RECORD,,
