databridge/__init__.py,sha256=J7SYX-BhYZMU-mzd1rIwQI7KK-kFG6GzpVrqKI4lZq8,198
databridge/client.py,sha256=F3nsI-Ip4Dy69qqXvVwKFrPXC5Njjs8cpN6eaninnlQ,6101
databridge/exceptions.py,sha256=3jqkdWNxOmPudpBR2Fjze6xcfk4235RXvbLMY0dpA3M,268
databridge_client-0.1.0.dist-info/METADATA,sha256=A5I-B5Al12tN43sNz6_nplQWl7kZ7E9LRkJkT_dcin0,953
databridge_client-0.1.0.dist-info/WHEEL,sha256=C2FUgwZgiLbznR-k0b_5k3Ai_1aASOXDss3lzCUsUug,87
databridge_client-0.1.0.dist-info/RECORD,,
